"""add_viral_referral_fields

Revision ID: 16e52ca1c00b
Revises: 4c58aa1aa8bf
Create Date: 2026-02-26 10:45:14.238189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e52ca1c00b'
down_revision: Union[str, None] = '4c58aa1aa8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ref_code', sa.String(length=8), nullable=True))
    op.add_column('leads', sa.Column('referred_by', sa.String(length=8), nullable=True))
    op.add_column('leads', sa.Column('share_token', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_leads_ref_code'), 'leads', ['ref_code'], unique=True)
    op.create_index(op.f('ix_leads_referred_by'), 'leads', ['referred_by'], unique=False)
    op.create_index(op.f('ix_leads_share_token'), 'leads', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_share_token'), table_name='leads')
    op.drop_index(op.f('ix_leads_referred_by'), table_name='leads')
    op.drop_index(op.f('ix_leads_ref_code'), table_name='leads')
    op.drop_column('leads', 'share_token')
    op.drop_column('leads', 'referred_by')
    op.drop_column('leads', 'ref_code')
    # ### end Alembic commands ###
