"""initial schema

Revision ID: 4c58aa1aa8bf
Revises: 
Create Date: 2026-02-24 23:44:32.276728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c58aa1aa8bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('base_postcode', sa.String(length=10), nullable=True),
    sa.Column('base_lat', sa.Float(), nullable=True),
    sa.Column('base_lng', sa.Float(), nullable=True),
    sa.Column('service_radius_miles', sa.Integer(), nullable=True),
    sa.Column('pref_min_cbm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pref_max_cbm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pref_property_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pref_notification_email', sa.String(length=255), nullable=True),
    sa.Column('pref_notification_phone', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_stripe_customer_id'), 'companies', ['stripe_customer_id'], unique=True)
    op.create_table('lead_pricing_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_cbm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_cbm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('pickup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dropoff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('dropoff_property_type', sa.String(length=100), nullable=True),
    sa.Column('move_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dropoff_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('total_cbm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('bulky_items', sa.Integer(), nullable=True),
    sa.Column('fragile_items', sa.Integer(), nullable=True),
    sa.Column('estimate_low', sa.Integer(), nullable=True),
    sa.Column('estimate_high', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_price_pence', sa.Integer(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_status_submitted', 'leads', ['status', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_leads_customer_email'), 'leads', ['customer_email'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_token'), 'leads', ['token'], unique=True)
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_event_type'), 'stripe_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stripe_events_stripe_event_id'), 'stripe_events', ['stripe_event_id'], unique=True)
    op.create_table('lead_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notification_method', sa.String(length=20), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_company_lead', 'lead_notifications', ['company_id', 'lead_id'], unique=False)
    op.create_index(op.f('ix_lead_notifications_company_id'), 'lead_notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_notifications_lead_id'), 'lead_notifications', ['lead_id'], unique=False)
    op.create_table('lead_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index('idx_purchase_company_lead', 'lead_purchases', ['company_id', 'lead_id'], unique=True)
    op.create_index(op.f('ix_lead_purchases_company_id'), 'lead_purchases', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_purchases_lead_id'), 'lead_purchases', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_purchases_payment_status'), 'lead_purchases', ['payment_status'], unique=False)
    op.create_table('lead_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_rooms_lead_id'), 'lead_rooms', ['lead_id'], unique=False)
    op.create_table('lead_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('length_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cbm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bulky', sa.Boolean(), nullable=True),
    sa.Column('fragile', sa.Boolean(), nullable=True),
    sa.Column('item_category', sa.String(length=50), nullable=True),
    sa.Column('packing_requirement', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['lead_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_items_room_id'), 'lead_items', ['room_id'], unique=False)
    op.create_table('lead_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['lead_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_photos_room_id'), 'lead_photos', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_photos_room_id'), table_name='lead_photos')
    op.drop_table('lead_photos')
    op.drop_index(op.f('ix_lead_items_room_id'), table_name='lead_items')
    op.drop_table('lead_items')
    op.drop_index(op.f('ix_lead_rooms_lead_id'), table_name='lead_rooms')
    op.drop_table('lead_rooms')
    op.drop_index(op.f('ix_lead_purchases_payment_status'), table_name='lead_purchases')
    op.drop_index(op.f('ix_lead_purchases_lead_id'), table_name='lead_purchases')
    op.drop_index(op.f('ix_lead_purchases_company_id'), table_name='lead_purchases')
    op.drop_index('idx_purchase_company_lead', table_name='lead_purchases')
    op.drop_table('lead_purchases')
    op.drop_index(op.f('ix_lead_notifications_lead_id'), table_name='lead_notifications')
    op.drop_index(op.f('ix_lead_notifications_company_id'), table_name='lead_notifications')
    op.drop_index('idx_notification_company_lead', table_name='lead_notifications')
    op.drop_table('lead_notifications')
    op.drop_index(op.f('ix_stripe_events_stripe_event_id'), table_name='stripe_events')
    op.drop_index(op.f('ix_stripe_events_event_type'), table_name='stripe_events')
    op.drop_table('stripe_events')
    op.drop_index(op.f('ix_leads_token'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_email'), table_name='leads')
    op.drop_index('idx_leads_status_submitted', table_name='leads')
    op.drop_table('leads')
    op.drop_table('lead_pricing_tiers')
    op.drop_index(op.f('ix_companies_stripe_customer_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
